# Generated by Django 6.0.2 on 2026-03-27 11:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='jobrole',
            name='description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='project',
            name='related_job',
        ),
        migrations.AddField(
            model_name='jobrole',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
        migrations.AddField(
            model_name='jobrole',
            name='company_name',
            field=models.CharField(default='Unknown Company', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobrole',
            name='projects',
            field=models.ManyToManyField(blank=True, to='career.project'),
        ),
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobrole',
            name='skills_required',
            field=models.ManyToManyField(blank=True, to='career.skill'),
        ),
        migrations.AlterField(
            model_name='jobrole',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='users', to='career.skill'),
        ),
    ]
