# Generated by Django 6.0.2 on 2026-04-11 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0002_alter_project_options_alter_skill_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
        migrations.RemoveField(
            model_name='project',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
        migrations.AddField(
            model_name='project',
            name='skills',
            field=models.ManyToManyField(blank=True, to='career.skill'),
        ),
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
